name: TOC Generator
description: GitHub Action to generate TOC.
author: technote-space
inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    required: true
  TARGET_PATHS:
    description: Target file path. (Comma separated, @see https://github.com/thlorenz/doctoc#adding-toc-to-individual-files)
    default: 'README.md'
  TOC_TITLE:
    description: TOC Title
    default: '**Table of Contents**'
  COMMIT_MESSAGE:
    description: Commit message.
    default: 'docs: Update TOC'
  INCLUDE_LABELS:
    description: Labels used to check if the PR has it.
    default: ''
  BRANCH_PREFIX:
    description: Branch name prefix.
    default: ''
branding:
  icon: 'book-open'
  color: 'blue'
runs:
  using: node12
  main: lib/main.js
